products_emojis = {
    "Smartphone": "📱",
    "LED TV": "📺",
    "Laptop": "💻",
    "Sofa Set": "🛋️",
    "Dining Table": "🍽️",
    "Bed": "🛏️",
    "Wardrobe": "🛁",
    "Study Table": "📝",
    "Rice": "🍚",
    "Dal": "🍲",
    "Cooking Oil": "🛢️",
    "Atta": "🌾",
    "Sugar": "🍬",
    "Men's Shirt": "👕",
    "Men's Jeans": "👖",
    "Men's T-Shirt": "👕",
    "Saree": "👗",
    "Kurti": "👚",
    "Women's Jeans": "👖",
    "Sports Shoes": "👟",
    "Sandals": "👡",
    "Formal Shoes": "👞",
    "Mixer Grinder": "🍲",
    "Induction Cooktop": "🍳",
    "Rice Cooker": "🍚",
    "Wall Clock": "🕰️",
    "Curtains": "🪟",
    "Bedsheet": "🛏️",
    "Shampoo": "🧴",
    "Face Wash": "🧴",
    "Toothpaste": "🪥",
    "Notebook": "📓",
    "Pen Set": "🖊️",
    "Novel": "📚",
    "Yoga Mat": "🧘‍♀️",
    "Dumbbells": "🏋️‍♀️",
    "Cricket Bat": "🏏",
    "Building Blocks": "🧩",
    "Remote Car": "🚗",
    "Board Game": "🎲", 
}